"""
Django settings for chat project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!nv6h$=@!80cdf%jyx5$o%)!&_hg9_$ko(1#0rdtvjb*ip0m2t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# CSRF_COOKIE_SECURE = True

ALLOWED_HOSTS = []


CRISPY_TEMPLATE_PACK='bootstrap3'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chatterbot.ext.django_chatterbot',
    'bot',
    'chatt',
    'crispy_forms',
]



# CHATTERBOT = {
#     'name': 'Chat Bot',
#     'django_app_name': 'django_chatterbot',
#
#     # 'storage_adapter': 'chatterbot.storage.SQLStorageAdapter',
#     'database_uri': 'sqlite:///online_bot_database.sqlite3',
#     'logic_adapters': [
#         {
#             'import_path': 'chatterbot.logic.BestMatch',
#             'default_response': 'I am sorry, but I do not understand.',
#             'maximum_similarity_threshold': 0.1,
#             # 'input_text': 'Help me!',
#             # 'output_text': 'Ok, here is a link: http://chatterbot.rtfd.org'
#         },
#         {
#             'import_path': 'chatterbot.logic.MathematicalEvaluation',
#         },
#         {
#             'import_path': 'chatterbot.logic.SpecificResponseAdapter',
#             'input_text': 'Help me!',
#             'output_text': 'Ok, here is a link: http://chatterbot.rtfd.org'
#         },
#     ],
#     'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
#     'storage_adapter': 'chatterbot.storage.DjangoStorageAdapter',
#     'training_data': [
#         "chatterbot.corpus.english.conversations",
#         # "chatterbot.corpus.spanish",
#         # "chatterbot.corpus.italian",
#         # "chatterbot.corpus.french",
#         # "chatterbot.corpus.russian"
#     ]
# }


CHATTERBOT = {
    'name': 'Chat',
    'django_app_name': 'django_chatterbot',

    'storage_adapter': 'chatterbot.storage.DjangoStorageAdapter',
    'database_uri': 'sqlite:///chatbot_.sqlite3',
    'logic_adapters': [
        {
            'import_path': 'chatterbot.logic.BestMatch',
            'default_response': 'I am sorry, but I do not understand.',
            'maximum_similarity_threshold': 0.1
        }
    ],
    'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
    'training_data': [
        "./bot/my_export.json",
    ]
}


# bot = ChatBot('Pinaki',
#               storage_adapter='chatterbot.storage.SQLStorageAdapter',
#
#     logic_adapters=[
#         {
#             'import_path': 'chatterbot.logic.BestMatch',
#             'default_response': 'I am sorry, but I do not understand.',
#             'maximum_similarity_threshold': 0.90
#         }
#     ]
#               )










MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
